# Site settings
title: See as you can
email: youngyoungju@gmail.com
github_username:  yangyju

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

 github: [metadata]
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate
